// ignore_for_file: file_names

const digestingOverview = '   Sistem pencernaan ialah sistem yang terdiri dari saluran pencernaan yang juga kerap disebut sebagai saluran GI, ditambah oleh ahli, pankreas, sampai kantung empedu. Saluran pencernaan sendiri adalah serangkaian organ berongga yang tergabung dalam tabung panjang yang memutar, dari mulut sampai anus.'
  '\n   Organ-organ berongga yang termasuk dalam saluran pencernaan, seperti mulut, kerongkongan, lambung, usus halus dan usus besar, sampai anus. Kalau hati, pankreas, dan kantung empedu, termasuk sistem pencernaan sebagai organ padat.'
  '\n   Di saluran pencernaan kita, terdapat bakteri flora normal atau mikrobioma yang membantu pencernaan. Selain itu, bagian dari sistem peredaran darah dan tautan eksternal NIH kita juga membantu. Mereka bekerja bersama hormon, saraf, darah, bakteri, sampai organ pencernaan kita dalam mencerna makanan dan cairan yang kita konsumsi setiap hari.';
const whatHappenToFood = '    Sebagian besar nutrisi pada makanan kita diserap oleh usus kecil. Sementara itu, sistem peredaran darah akan meneruskannya ke bagian tubuh lain untuk disimpan atau digunakan.'
  ' Dalam hal itu, sel-sel khusus membantu nutrisi yang diserap melewati lapisan usus ke dalam darah kira.'
  '\n   Ada pula jaringan pembuluh yang membawa sel darah putih dan getah bening ke seluruh tubuh untuk melawan infeksi, menyerap asam lemak, dan vitamin, yang disebut sistem getah bening.'
  '\n   Tubuh kita pun akan bisa menggunakan asam amino, gula, asam lemak, dan gliserol untuk membangun zat-zat sebagai keperluan energi, pertumbuhan, dan perbaikan sel.';
const mouthContent = '    Awal dari saluran pencernaan ialah organ mulut. Pada bagian ini terdapat beberapa alat yang akan membantu dalam proses pencernaan diantaranya: gigi, lidah serta kelenjar ludah atau air liur. Di dalam rongga mulut ini makanan akan mengalami proses pencernaan secara mekanik dan kimiawi.'
  '\n   Proses Pencernaan secara mekanik akan dilakukan oleh gigi. Gigi ini memiliki fungsi untuk mengunyah makanan agar menjadi halus. Gigi sendiri dibedakan menjadi empat macam yang tergantung pada letak dan fungsinya, seperti gigi seri, gigi taring, gigi geraham depan dan gigi geraham belakang.'
  ' Sedangkan Proses Pencernaan secara kimiawi dilakukan oleh Enzim Ptialin yang dihasilkan oleh kelenjar ludah, Enzim ptialin berfungsi memecah karbohidrat (polisakarida) menjadi Maltosa (monosakarida).';
const kerongkonganContent = '   Kerongkongan atau dikenal dengan esofagus adalah saluran penghubung antara rongga mulut dengan bagian lambung. Organ ini memiliki fungsi sebagai jalan bagi makanan yang telah dikunyah dari rongga mulut menuju lambung. Jadi pada bagian kerongkongan ini hanya menyalurkan makanan ke lambung dan tidak terjadi pencernaan di sana.'
  ' Saat terjadi proses penyaluran ke lambung, lipatan kecil bernama epiglotis akan melipat di atas tenggorokan saat itu, agar makanan tidak salah masuk ke trakea yang merupakan saluran pernapasan. Jika itu terjadi, kita akan tersedak.'
  '\n   Dengan kontraksi otot yang membentuk gerakan peristaltik di kerongkongan, makanan akan diantar dari mulut ke perut kita. Meski begitu, otot semacam cincin pada bagian bawah kerongkongan yang dinamakan sfingter esofagus harus rileks agar makanan bisa masuk.'
  ' Otot itu kemudian berkontraksi dan mencegah isi perut kembali mengarah ke kerongkongan. Jika sfingter esofagus tidak berkontraksi dan makanan mengarah kembali ke kerongkongan, kita bisa jadi akan mengalami mulas atau refluks asam.';
const lambungContent = '    Organ lambung atau lebih dikenal dengan istilah Ventrikulus merupakan kantung besar yang terletak di sebelah kiri dari rongga perut yang berfungsi sebagai tempat terjadinya sejumlah proses pencernaan.'
  ' Di dalam lambung terjadi proses pemecahan menjadi bentuk yang bisa digunakan oleh tubuh. Sel-sel dalam lapisan lambung akan mengeluarkan asam dan enzim kuat yang bertugas melakukannya. Selanjutnya makanan akan dibawa ke usus kecil.'
  '\n   Enzim yang terdapat pada lambung yaitu enzim Renin dan enzim Lipase. Enzim renin berfungsi mengubah protein susu(Kaseinogen) menjadi Kasein(dengan bantuan Kalsium). Sedangkan enzim Pepsin berfungsi mengubah Protein menjadi Pepton';
const pancreasContent = '   Enzim pencernaan adalah enzim yang dikeluarkan pankreas ke dalam duodenum yang akan memecah protein, lemak, dan karbohidrat. Organ ini juga yang menciptakan insulin dan meneruskannya ke aliran darah. Sebagai informasi, insulin merupakan hormon utama untuk metabolisme gula dalam tubuh kita.';
const empeduContent = '   Organ kantung empedu bertugas menyimpan dan mengkonsentrasikan empedu dari hati untuk kemudian dilepaskan ke duodenum di usus kecil yang akan membantu menyerap dan mencerna lemak.';
const ususHalusContent = '    Usus halus atau dikenal dengan istilah Intestinum ini merupakan tempat penyerapan sari makanan dan juga sebagai tempat terjadinya proses pencernaan yang paling panjang. Pada organ usus ini terdapat beberapa bagian, di antaranya:'
  '\n 1. Usus dua belas jari atau dikenal dengan istilah duodenum.'
  '\n 2. Usus kosong atau jejenum.'
  '\n 3. Usus Penyerapan atau ileum.'
  '\n   Tabung otot sepanjang 22 kaki yang memecah makanan dengan enzim dari pankreas dan empedu dari hati inilah usus halus. Organ ini juga punya gerakan peristaltik yang memudahkan pergerakan makanan dan pencampuran dengan cairan pencernaan dari pankreas dan hati.'
  '\n   Dalam usus kecil, duodeni, bertugas memproses kelambatan pencernaan yang berkelanjutan. Sementara itu, jejunum dan ileum yang berada lebih rendah bertugas dalam penyerapan nutrisi ke dalam aliran darah.'
  '\n   Makanan yang diolah di usus halus awalnya berbentuk setengah padat dan berakhir dengan bentuk cair. Hal ini karena adanya kontribusi antara air, empedu, enzim, dan lendir dalam perubahan konsistensi tersebut. Makanan akan dipindahkan ke usus besar setelah nutrisi telah diserap dan sisa makanan melewati usus kecil.';
const ususBesarContent = '    Organ ini ialah otot berbentuk tabung sepanjang 6 kaki yang menghubungkan usus kecil dengan rektum. Usus besar ini terdiri dari sekum, kolon asendens, kolon transversum, kolon desendens, dan kolon sigmoid yang terhubung ke rektum.'
  '\n   Limbah makanan atau kotoran yang tersisa dari proses pencernaan akan melewati usus besar dengan gerakan peristaltik, dan mulanya berbentuk cair dan akhirnya menjadi bentuk padat. Setelah tinja melewati usus besar, air akan keluar dan kotoran pun disimpan di kolon sigmoid sampai gerakan mengarahkannya ke rektum dalam sehari atau dua hari sekali.'
  '\n   Umumnya, butuh sekitar 36 jam hingga tinja bisa melewati usus besar. Kotoran yang terdapat di sana pun sebagian besarnya ialah sisa makanan dan bakteri. Beberapa fungsi berguna akan dilakukan oleh bakteri baik, seperti memproses limbah dan bakteri makanan, mensintesis berbagai vitamin, sampai melindungi kita dari bakteri berbahaya.';
const rektumContent = '   Ruang lurus berukuran 8 inci ialah rektum yang menghubungkan usus besar dengan anus. Rektum sendiri bertugas menerima feses dari usus besar, memberi sinyal kepada kita bahwa ada kotoran yang harus dikeluarkan. Saat ada sesuatu berupa gas atau tinja yang masuk ke rektum, sensor akan mengirim pesan ke otak kita yang akhirnya memutuskan kemungkinan pengeluaran kotoran.'
  '\n   Jika menurut otak kita, kotoran itu bisa dikeluarkan saat itu juga, maka sfingter akan mengendur dan rektum akan berkontraksi untuk membuangnya. Jika feses belum bisa dibuang saat itu, sfingter justru akan berkontraksi dan rektum berakomodasi, sehingga sensasi mulas hilang untuk sementara.';
const anusContent = '   Bagian atau organ terakhir dari sistem pencernaan adalah anus. Anus sendiri merupakan saluran yang panjangnya 2 inci, terdiri atas otot-otot dasar panggul dan dua sfingter anal (internal dan eksternal). Bagian atas lapisan anus bisa mendeteksi isi rektal. Inilah yang memungkinkan kita untuk tahu apakah isinya padat, cair, atau gas saja.'
  '\n   Pada anus, terdapat otot sfingter yang mengelilingi dan berfungsi mengontrol feses. Sudut tercipta antara rektum dan anus karena otot dasar panggul. Sudut tersebut berguna untuk mencegah tinja keluar di saat yang tidak seharusnya.'
  '\n   Sfingter internal sendiri selalu kencang kecuali saat feses masuk ke rektum. Dengan demikian, kita tidak akan bisa buang air besar dengan tidak sadar, seperti saat kita tidur nyenyak.'
  ' Saat terdorong untuk pergi ke toilet, kita akan mengandalkan sfingter eksternal untuk menahan tinja sampai tiba di toilet. Setelahnya, barulah ia rileks untuk mengeluarkan feses.';
const digestingProcess = '    Proses pencernaan akan dimulai saat makanan masuk ke dalam mulut. Makanan akan mengalami proses pencernaan secara mekanik dan kimiawi. Gigi akan memotong makanan menjadi bentuk yang lebih kecil, lalu melumatnya dengan bantuan lidah, langit-langit mulut, dan pipi bagian dalam.'
  ' Pada saat yang sama, pencernaan kimiawi juga terjadi. Air liur yang mengandung enzim ptialin akan memecah amilum menjadi maltose. Hal ini bertujuan agar fungsi lambung dapat berjalan dengan lebih mudah. Selanjutnya makanan akan didorong masuk kerongkongan dan menuju lambung dengan gerakan otot.'
  '\n   Makanan yang telah berbentuk lumat akan masuk ke dalam lambung. Selanjutnya makanann akan digiling menggunakan otot-otot lambung yang berlapis-lapis, lalu mencampurnya dengan asam dan enzim-enzim seperti pepsin, dan renin. Setelah proses pencernaan dalam lambung selesai, makanan kini menjadi bubur halus.'
  ' Bubur halus ini akan menunggu waktu pengosongan lambung sebelum akhirnya bergerak menuju usus halus untuk tahapan pencernaan selanjutnya.'
  '\n   Saat usus halus mendeteksi makanan, kantong empedu akan berkontraksi untuk mengeluarkan cairan empedu. Cairan ini sebelumnya diproduksi oleh organ hati dengan fungsi untuk menguraikan makanan. Pada saat yang sama, organ pankreas akan melepaskan enzim amilase, lipase, tripsin dan beberapa enzim lainnya.'
  ' Zat gizi yang telah berbentuk molekul kecil lalu bergerak menuju pembuluh darah pada usus halus. Darah kemudian mengedarkan zat gizi ke seluruh tubuh, sedangkan ampas makanan meninggalkan usus.'
  '\n   Proses pencernaan berlanjut dengan makanan bergerak menuju organ usus besar. Makanan yang telah menjadi ampas tidak lagi menjalani pencernaan mekanik atau kimiawi. Pasalnya, usus halus telah menyerap setiap zat gizi dari makanan.'
  '\n   Di sini, ampas makanan akan melewati proses penyesuaian kadar air. Usus besar akan menambah atau menyerap kandungan air untuk menghasilkan kepadatan feses yang sesuai. Ampas makanan juga mengalami pembusukan oleh bakteri dalam usus.'
  '\n   Feses dari usus besar kemudian bergerak menuju rektum. Sebelum Anda buang air besar (BAB), rektum akan menampung feses untuk sementara waktu. Begitu rektum penuh, barulah Anda merasakan sensasi mulas yang menandakan saatnya buang air besar. Feses keluar melalui ujung saluran pencernaan yang disebut anus.'
  ' Area ini terdiri atas sekumpulan otot yang akan berkontraksi saat Anda merasa mulas. Keluarnya feses dari anus menandakan akhir dari proses pencernaan makanan.'
  '\n   Setiap orang memiliki kondisi pencernaan dan respons yang berbeda-beda terhadap makanan tertentu. Inilah mengapa setiap orang membutuhkan waktu yang berbeda untuk menuntaskan pencernaan makanan dalam tubuhnya.'
  ' Perjalanan makanan dari mulut hingga anus setidaknya memakan waktu sekitar 24 – 72 jam. Menurut penelitian oleh Mayo Clinic, proses pencernaan pria rata-rata berlangsung selama 33 jam, sedangkan wanita kurang-lebih 47 jam.';
const digestingDiease1 = '    Sembelit umumnya terjadi ketika kita buang air besar lebih jarang dari biasanya. Saat sembelit, kotoran kita sering kering dan keras, jadi sulit dan menyakitkan untuk buang air besar.';
const digestingDiease2 = '    Diare adalah ketika kita punya kotoran yang encer atau berair. Diare dapat disebabkan oleh banyak hal, termasuk bakteri, tetapi terkadang penyebabnya tidak diketahui.';
const digestingDiease3 = '    Wasir bengkak, pembuluh darah membesar yang terbentuk di dalam dan di luar anus dan rektum kita. Mereka bisa menyakitkan, tidak nyaman dan menyebabkan pendarahan dubur.';
const digestingDiease4 = '    Flu perut adalah infeksi pada lambung dan usus halus bagian atas yang biasanya disebabkan oleh virus. Biasanya, ini berlangsung kurang dari seminggu. Sebenarnya, jutaan orang terkena flu perut setiap tahun.';
const digestingDiease5 = '    Bisul adalah luka yang berkembang pada lapisan kerongkongan, lambung atau usus kecil. Penyebab paling umum dari bisul adalah infeksi bakteri yang disebut Helicobacter pylori (H. pylori) dan penggunaan obat antiinflamasi jangka panjang seperti ibuprofen.';
const digestingDiease6 = '    Batu empedu adalah potongan kecil bahan padat yang terbentuk dari cairan pencernaan yang terbentuk di kantong empedu, organ kecil di bawah hati kita.';
const howToKeepHealtyDigestive = '    Jika memiliki kondisi medis, selalu tanyakan kepada dokter soal apa yang harus kita lakukan. Jangan lupa makan agar tetap sehat dan bisa mengelola kondisi. Secara umum, berikut ini adalah cara menjaga kesehatan sistem pencernaan:'
  '\n 1. Sering minum air'
  '\n 2. Makan yang berserat'
  '\n 3. Makan makanan yang seimbang'
  '\n 4. Makan makanan dengan kandungan probiotik atau minum suplemen probiotik'
  '\n 5. Jangan terburu-buru dan kunyah makanan dengan baik'
  '\n 6. Lakukan latihan olahraga'
  '\n 7. Hindari rokok dan alkohol'
  '\n 8. Kelola stres';

