// ignore_for_file: file_names

const String respirationIntroduction = '   Sistem Pernapasan atau yang disebut juga dengan sistem respirasi adalah suatu proses yang dilakukan makhluk hidup untuk pengambilan Oksigen (O2) dan pelepasan Karbon Dioksida (CO2).'
  ' Ketika manusia bernapas maka sedang terjadi proses masuknya oksigen ke dalam tubuh dan pelepasan karbon dioksida dari dalam tubuh. Proses pertukaran antara oksigen dengan karbon dioksida dalam tubuh manusia terjadi di dalam aliran darah,'
  ' dimana darah yang awalnya membawa oksigen akan berganti membawa karbon dioksida. Tujuan dari proses pernapasan yaitu untuk memperoleh energi. Seseorang memiliki laju pernapasan normal apabila ia bernapas 12 hingga 20 kali per menit,'
  ' akan tetapi jika seseorang melakukan aktivitas berat seperti berolahraga maka kebutuhan O2 akan meningkat.';

const String respirationFunction1 = '   Fungsi pertama dari sistem pernapasan yaitu untuk proses bernapas. Udara akan dihirup masuk melalui mulut atau hidung yang mana selanjutnya akan disalurkan menuju paru-paru dan pada akhirnya akan dikeluarkan dari tubuh melalui mulut atau hidung.'
  ' Saat menghembuskan napas, otot-otot menjadi rileks, paru-paru mengempis dan udara akan dikeluarkan.';
const String respirationFunction2 = '   Saat proses pernapasan berlangsung, di dalam paru-paru, akan terjadi proses pertukaran oksigen dengan karbon dioksida. Proses ini disebut dengan respirasi eksternal dan terjadi di alveoli. Oksigen akan mengikat molekul hemoglobin dalam sel darah merah yang kemudian akan menyebar melalui aliran peredaran darah.';
const String respirationFunction3 = '   Aliran darah akan mengalirkan oksigen ke sel tubuh dan membuang limbah karbon dioksida. Proses ini disebut dengan respirasi internal. Pada proses ini, sel darah merah akan membawa oksigen yang diserap oleh paru-paru ke seluruh tubuh melalui peredaran darah.';
const String respirationFunction4 = '   Pada saat proses penciuman berlangsung, itu akan dimulai dari serat penciuman pada lapisan rongga hidung. Ketika udara masuk ke rongga hidung, bahan-bahan kimia di udara akan mengaktifkan reseptor sistem saraf. Stimulus ini akan mengirimkan sinyal ke otak. Sinyal tersebut akan bergerak dan dari situlah manusia bisa mengenali bau.';
const String respirationFunction5 = '   Selama bernapas udara akan mengalir dari paru-paru ke kotak suara. Saat manusia berbicara otot di laring akan menggerakkan tulang rawan aritenoid, selanjutnya akan mendorong pita suara.'
  ' Getaran yang besar pada pita suara akan menghasilkan suara bernada tinggi. Sedangkan getaran yang kecil akan membuat suara bernada rendah.';

const String respirationOrganOverview = '   Sistem pernapasan dalam tubuh manusia terdiri atas 6 organ yang memiliki peran masing-masing. Organ-organ penyusun sistem pernapasan yaitu Rongga Hidung, Faring, Trakea, Laring, Bronkus, dan Paru-paru.';
const String respirationOrgan1 = '    Saat bernapas, pertama kali udara akan masuk ke rongga hidung. Di sini udara akan disaring oleh selaput hidung yang mengandung kelenjar minyak dan kelenjar keringat. Selaput ini berguna untuk menangkap benda-benda asing agar tidak ikut masuk dalam saluran pernapasan bersama udara.'
  ' Pada rongga hidung juga terdapat bulu-bulu hidung yang berguna sebagai penyaring udara. Selain itu ada juga konka yang memiliki fungsi untuk menghangatkan udara dingin yang masuk ke dalam rongga hidung.';
const String respirationOrgan2 = '    Setelah penyaringan di rongga hidung, udara kemudian masuk melewati laring atau tenggorokan. Tenggorokan terdiri dari dua saluran, yakni saluran pencernaan serta saluran pernapasan. Fungsi dari tenggorokan dalam sistem pernapasan adalah menyediakan saluran untuk keluar masuk udara.'
  ' Saat udara melewati tenggorokan, pita suara yang terdapat di organ ini bergetar dan menghasilkan suara.'
  '\n   Jika seseorang makan sambil berbicara hal itu bisa membahayakan karena makanan bisa masuk ke saluran pernapasan yang sedang terbuka. Meski begitu, saraf manusia bisa mengatur supaya menelan, bernapas dan berbicara tidak terjadi dalam waktu yang bersamaan. Jika hal ini sering dilakukan bisa menimbulkan gangguan kesehatan.';
const String respirationOrgan3 = '    Trakea atau batang tenggorokan terletak di depan kerongkongan. Trakea berfungsi sebagai jalan utama udara atau oksigen menuju paru-paru. Organ yang satu ini berbentuk seperti tabung berongga dengan panjang sekitar 10 cm dan diameter kurang dari 2,5 cm.'
  '\n   Batang tenggorokan ada di depan kerongkongan. Batang tenggorokan memiliki dua cabang. cabang dari tenggorokan itu akan bercabang-cabang lagi di dalam paru-paru dan menjadi saluran kecil yang disebut bronkiolus.';
const String respirationOrgan4 = '    Laring atau pangkal tenggorokan organ pernapasan yang berbentuk seperti saluran dan dikelilingi oleh tulang rawan. Pangkal tenggorokan memiliki tulang rawan yang disebut dengan epiglotis. Tulang rawan ini ada di bagian pangkal laring.'
  '  Pangkal tenggorokan juga diselimuti oleh membran yang bernama mukosa. Membran tersebut memiliki epitel-epitel berlapis yang cukup tebal untuk menahan getaran-getaran suara yang sampai pada pangkal tenggorokan.'
  '\n   Fungsi utama dari pangkal tenggorokan adalah sebagai tempat keluarnya masuk udara dan juga tempat menghasilkan suara. Di sinilah jantuk terbentuk yang disusun oleh beberapa tulang rawan pangkal tenggorokan.'
  ' Di dalam pangkal tenggorokan juga terdapat katup. Ketika manusia sedang menelan makanan, katup pada pangkal tenggorokan akan menutup dan akan terbuka jika manusia sedang bernafas.';
const String respirationOrgan5 = '    Bronkus berfungsi sebagai penyedia jalan bagi udara terhirup yang masuk dan keluar dari dan ke paru-paru. Bronkus mempunyai struktur yang persis seperti batang tenggorokan, bedanya terletak pada kehadiran tulang rawan di cabang batang tenggorokan mempunyai bentuk yang tidak teratur.'
  '\n   Batang tenggorokan memiliki dua cabang yaitu cabang di sebelah kiri dan kanan. Kedua cabang itu mengarah kepada paru-paru dan bercabang lagi. Cabang-cabang kecil yang masuk ke dalam paru-paru disebut alveolus.';
const String respirationOrgan6 = '    Paru-paru terletak pada bagian atas rongga dada. Di bagian bawahnya terdapat diafragma dan di samping terdapat tulang rusuk.'
  ' Paru-paru terbagi menjadi dua bagian, yaitu bagian kanan dan kiri. Paru-paru bagian kanan terdiri dari tiga lobus, sedangkan paru-paru kiri memiliki dua lobus saja. Paru-paru diselimuti oleh selaput yang tipis.'
  '\n   Di dalam paru-paru terdapat cabang dari bronkus, alveolus dan pembuluh darah. Bronkiolus memiliki cabang-cabang lagi yang disebut dengan bronkiolus respirasi. Paru-paru menjadi tempat pertukaran oksigen (O2) dan karbon dioksida (CO2).';

const String respirationProcessOverview = '   Manusia memiliki dua mekanisme pernapasan. Ada pernapasan dada dan juga pernapasan perut. Lalu bagaimana perbedaan keduanya? Berikut adalah penjelasan mekanisme proses pernapasan manusia.';
const String respirationChest = '   Ketika kita bernapas menggunakan dada, otot yang berperan adalah otot-otot di sekitar tulang rusuk. Otot-otot ini dibagi menjadi dua yaitu otot tulang rusuk luar dan tulang rusuk dalam. otot tulang rusuk luar memiliki peran untuk mengangkat tulang-tulang rusuk. Sedangkan otot tulang rusuk dalam memiliki fungsi untuk menurunkan tulang rusuk ke posisi normal.'
  '\n   Jika otot-otot pada tulang rusuk luar mengalami kontraksi, tulang rusuk akan terangkat sehingga volume di dada menjadi lebih besar. Hal ini akan menyebabkan tekanan di dalam rongga dada menjadi lebih kecil. Karena tekanan udara yang di dalam rongga dada mengecil, akan menyebabkan aliran udara masuk dari luar tubuh ke dalam tubuh. Proses ini disebut dengan inspirasi.'
  '\n   Apabila kontraksi dari otot dalam tulang rusuk, dan tulang rusuk kembali pada posisi semula, maka akan menyebabkan tekanan udara di dalam tubuh menjadi bertambah. Hal ini akan menimbulkan udara di dalam paru-paru tertekan pada rongga dada sehingga aliran udara akan terdorong ke luar tubuh. Proses ini lah yang disebut dengan ekspirasi.';
const String respirationStomach = '   Pernapasan dada atau disebut juga dengan pernapasan diafragma adalah pernapasan yang menggunakan diafragma dan otot dinding di rongga perut. otot diafragma akan berkontraksi dan posisinya menjadi datar. Hal ini menyebabkan volume rongga dada menjadi bertambah besar dan tekanan udara menjadi kecil. Karena tekanan udaranya yang rendah, paru-paru akan mengembang. Saat itulah terjadi masuknya udara ke paru-paru atau proses menghirup udara.'
  '\n   Sedangkan proses ekspirasi pernapasan perut, terjadi jika otot diafragma menjadi rileks dan otot yang ada di dinding perut menjadi kontraksi. Hal ini akan menyebabkan bagian dalam rongga perut menjadi terdesak ke arah diafragma. Sehingga hal tersebut menyebabkan posisi diafragma menjadi cekung ke arah rongga dada.'
  '\n   Sebetulnya, manusia terlahir secara alamiah bernapas menggunakan diafragma sepenuhnya. Sehingga napas yang diambil bisa lebih dalam. Namun, seiring bertambahnya usia, manusia tidak lagi melakukan kebiasaan bernapas menggunakan diafragma ini. Segala sesuatu kegiatan sehari-hari tanpa kita sadari memaksa kita untuk secara bertahap beralih ke pernapasan dada.'
  '\n   Ketika bernapas dengan diafragma atau pernapasan perut, akan mendorong pertukaran oksigen lebih maksimal dibanding pernapasan dada. Tidak heran bahwa pernapasan perut akan memperlambat detak jantung dan bisa menurunkan tekanan darah.';
const String respirationProcess = '1. Ketika menarik napas atau inhalasi, diafragma dan otot-otot di antara tulang rusuk akan berkontraksi dan meluaskan rongga dada sehingga paru-paru bisa mengembang dan terisi udara.'
  '\n2. Udara masuk lewat hidung atau mulut, kemudian melewati proses penyaringan partikel kecil oleh rambut hidung jika masuk melalui lubang hidung, lalu menuju ke trakea atau batang tenggorokan.'
  '\n3. Udara dari trakea masuk ke paru-paru melewati saluran pernapasan yang disebut dengan bronkus dan bronkiolus, kemudian berujung di alveolus.'
  '\n4. Ketika udara mencapai alveolus, terjadi proses pertukaran antara oksigen dan karbon dioksida pada pembuluh darah kecil bernama kapiler.'
  '\n5. Oksigen masuk ke dalam kapiler, kemudian menumpang sel darah merah menuju ke jantung untuk disebarkan ke seluruh tubuh. Di saat yang bersamaan, karbon dioksida masuk dari kapiler ke rongga paru.'
  '\n6. Setelah pertukaran oksigen dan karbon dioksida selesai, otot diafragma dan tulang rusuk kembali rileks dan rongga dada kembali seperti semula. Udara yang mengandung karbon dioksida pun terdorong dari alveolus menuju ke bronkiolus, bronkus, trakea, hingga ke luar melalui hidung.';

const String fluText = '    Gangguan ini disebabkan oleh virus influenza yang menginfeksi hidung, tenggorokan, dan paru-paru. Virus influenza bisa menyebar melalui udara, benda yang terkontaminasi, dan kontak fisik dengan penderita lain. Flu bisa dicegah dengan cara menjaga kebersihan, rajin mencuci tangan, tidak menyentuh wajah, dan menjauhi keramaian.';
const String asmaText = '   Asma merupakan jenis gangguan yang ditandai dengan peradangan pada saluran pernapasan. Gangguan ini dapat membuat saluran pernapasan menjadi menyempit. Penyebabnya bisa karena paparan asap, alergi, polusi, dan terkena udara dingin. Gejala asma yang sering dialami, diantaranya sesak napas, batuk, dan dada sesak.';
const String pneumoniaText = '    Sama dengan flu, pneumonia juga disebabkan oleh infeksi, virus, bakteri, atau jamur. Gangguan ini juga bisa disebabkan oleh virus SARS-CoV-2 yang menyebabkan Covid-19. Umumnya gejala pneumonia ditandai dengan batuk, demam, sesak napas, dan menggigil.';
const String tbcText = '    TBC adalah penyakit menular akibat infeksi bakteri Mycobacterium tuberculosis di paru-paru. TBC umumnya menyerang paru-paru, tetapi juga dapat menyerang organ tubuh lain, seperti ginjal, tulang belakang, dan otak. Penularan dapat terjadi ketika seseorang tidak sengaja menghirup percikan ludah (droplet) saat seseorang yang terinfeksi TBC bersin atau batuk';
const String bronkitisText = '    Bronkitis adalah iritasi atau peradangan di dinding saluran bronkus, yaitu pipa yang menyalurkan udara dari tenggorokan ke paru-paru. Bronkitis bisa terjadi dalam hitungan hari, minggu, bahkan bulan. Bronkitis yang memburuk dan tidak ditangani beresiko menyebabkan Pneumonia. Bronkitis dapat disebabkan oleh infeksi virus atau bakteri serta noninfeksi akibat kebiasaan merokok dan paparan debu atau polusi.';
const String howToKeepHealthy = '   Menjaga kesehatan tubuh bisa dimulai dengan menjaga kesehatan organ-organ tubuh, termasuk organ pernapasan. Cara menjaga kesehatan organ pernapasan bisa dengan rutin berolahraga, tidak merokok, menghindari asap rokok, hindari paparan populasi, dan menghindari infeksi.';
